//! Mechanical projection of pi's complete Files settings tab.
//!
//! `read.defaultLimit` and `read.summarize.prose` remain absent by ADR 0009:
//! the runtime owns one output bound and tools do not expose independent
//! truncation or prose-projection policy.

use super::*;

pub(super) const ENTRIES: &[UiSpec] = &[
	ui!(
		"edit.mode",
		"sv_tools_edit_dialect",
		Files,
		"Editing",
		"Edit Mode",
		"Select the edit tool variant (replace, patch, hashline, or apply_patch)",
		UiWidget::Enum(&["apply_patch", "hashline", "patch", "replace", "sloppy"]),
		None,
		EditModeRevision
	),
	ui!(
		"edit.fuzzyMatch",
		"sv_tools_edit_fuzzy",
		Files,
		"Editing",
		"Fuzzy Match",
		"Accept high-confidence fuzzy matches for whitespace differences",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"edit.fuzzyThreshold",
		"sv_edit_fuzzy_threshold",
		Files,
		"Editing",
		"Fuzzy Match Threshold",
		"Similarity threshold (0-1) for accepting fuzzy matches",
		UiWidget::Submenu(&[
			UiOption::new("0.85", "0.85", "Lenient"),
			UiOption::new("0.90", "0.90", "Moderate"),
			UiOption::new("0.95", "0.95", "Default"),
			UiOption::new("0.98", "0.98", "Strict")
		]),
		None,
		Identity
	),
	ui!(
		"edit.streamingAbort",
		"sv_tools_edit_streaming_abort",
		Files,
		"Editing",
		"Abort on Failed Preview",
		"Abort streaming edit tool calls when patch preview fails",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"edit.recoverInlineEdits",
		"sv_edit_recover_inline_edits",
		Files,
		"Editing",
		"Recover Inline Edit Payloads",
		"Execute edit payloads the model emits as plain text by converting them into edit tool calls",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"edit.blockAutoGenerated",
		"sv_tools_edit_guard_generated",
		Files,
		"Editing",
		"Block Auto-Generated Files",
		"Prevent editing of files that appear to be auto-generated (protoc, sqlc, swagger, etc.)",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"edit.enforceSeenLines",
		"sv_tools_edit_require_seen",
		Files,
		"Editing",
		"Enforce Seen-Line Guard",
		"Reject edits anchored on lines a prior read/search never displayed in full",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"edit.blackbox.enabled",
		"sv_tools_edit_blackbox_enabled",
		Files,
		"Editing",
		"Record Parse Regressions",
		"Append full before/after source when an edit introduces an AST parse failure",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"edit.autoRepair.enabled",
		"sv_tools_edit_auto_repair",
		Files,
		"Editing",
		"Auto-Repair Parse Regressions",
		"When an edit breaks a file's AST parse, ask the smol model to fix the broken region \
		 (validated by re-parse; falls back to a warning)",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"readLineNumbers",
		"sv_tools_read_line_numbers",
		Files,
		"Reading",
		"Line Numbers",
		"Prepend line numbers to read tool output by default",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"read.renderMarkdown",
		"cl_read_render_markdown",
		Files,
		"Reading",
		"Markdown Previews",
		"Render Markdown read results as formatted terminal Markdown previews instead of raw source",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"read.toolResultPreview",
		"sv_read_tool_result_preview",
		Files,
		"Reading",
		"Inline Read Previews",
		"Render read tool results inline in the transcript instead of summary rows",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"read.summarize.enabled",
		"sv_tools_read_summarize",
		Files,
		"Read Summaries",
		"Read Summaries",
		"Return structural code summaries when read is called without an explicit selector",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"read.summarize.minBodyLines",
		"sv_read_summarize_min_body_lines",
		Files,
		"Read Summaries",
		"Read Summary Body Lines",
		"Minimum multiline body or literal length before read summaries collapse it",
		UiWidget::ConfigOnly,
		None,
		Identity
	),
	ui!(
		"read.summarize.minCommentLines",
		"sv_read_summarize_min_comment_lines",
		Files,
		"Read Summaries",
		"Read Summary Comment Lines",
		"Minimum multiline block comment length before read summaries collapse it",
		UiWidget::ConfigOnly,
		None,
		Identity
	),
	ui!(
		"read.summarize.minTotalLines",
		"sv_read_summarize_min_total_lines",
		Files,
		"Read Summaries",
		"Read Summary Minimum File Length",
		"Files with fewer total lines are read verbatim instead of structurally summarized",
		UiWidget::ConfigOnly,
		None,
		Identity
	),
	ui!(
		"read.summarize.unfoldUntil",
		"sv_read_summarize_unfold_until",
		Files,
		"Read Summaries",
		"Read Summary Unfold Target",
		"BFS-unfold elidable spans until the summary is at least this many visible lines. 0 keeps \
		 only the outermost elisions.",
		UiWidget::ConfigOnly,
		None,
		Identity
	),
	ui!(
		"read.summarize.unfoldLimit",
		"sv_read_summarize_unfold_limit",
		Files,
		"Read Summaries",
		"Read Summary Unfold Ceiling",
		"Hard ceiling on summary size while BFS-unfolding. An unfold whose revealed lines would \
		 exceed this is skipped (that span stays folded) and unfolding continues with the remaining \
		 spans.",
		UiWidget::ConfigOnly,
		None,
		Identity
	),
	ui!(
		"lsp.enabled",
		"sv_lsp_enabled",
		Files,
		"LSP",
		"LSP",
		"Enable the lsp tool for code intelligence (definitions, references, diagnostics, rename)",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"lsp.lazy",
		"sv_lsp_lazy",
		Files,
		"LSP",
		"Lazy LSP Startup",
		"Start language servers on first use (lsp tool or editing a matching file type) instead of \
		 at session startup",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"lsp.shared",
		"sv_lsp_shared",
		Files,
		"LSP",
		"Shared Language Servers",
		"Share one language server per project across omp instances via the daemon broker (falls \
		 back to private servers when unavailable)",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"lsp.formatOnWrite",
		"sv_lsp_format_on_write",
		Files,
		"LSP",
		"Format on Write",
		"Automatically format code files using LSP after writing",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"lsp.diagnosticsOnWrite",
		"sv_lsp_diagnostics_on_write",
		Files,
		"LSP",
		"Diagnostics on Write",
		"Return LSP diagnostics after writing code files",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"lsp.diagnosticsOnEdit",
		"sv_lsp_diagnostics_on_edit",
		Files,
		"LSP",
		"Diagnostics on Edit",
		"Return LSP diagnostics after editing code files",
		UiWidget::Boolean,
		None,
		Identity
	),
	ui!(
		"lsp.diagnosticsDeduplicate",
		"sv_lsp_diagnostics_deduplicate",
		Files,
		"LSP",
		"Deduplicate Diagnostics",
		"Suppress post-edit LSP diagnostics already shown for a file; only surface new or changed \
		 ones",
		UiWidget::Boolean,
		None,
		Identity
	),
];
